# Generated by Django 2.0 on 2019-11-21 15:16

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='poster',
            field=models.ImageField(blank=True, help_text='Please upload an image with 16:9 resolution', null=True, upload_to=events.models.poster_upload_path),
        ),
    ]
